### ISSUE TITLE
Latest update nuked itself

### ISSUE THREAD

**Issue by maggar** [hassio-addons/addon-zwavejs2mqtt#178]
# Problem/Motivation
Ha auto updated zwavejs2mqtt and now zwavejsmqtt won't start.  Gives the following error on start.

404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_a0d7b954_zwavejs2mqtt: Not Found ("No such image: ghcr.io/hassio-addons/zwavejs2mqtt/amd64:0.17.0")
## Expected behavior
Starts correctly, with snapshot to recover to previous state

## Actual behavior

Won't start, no snapshot to recover

## Steps to reproduce

Auto update zwavejs2mqtt

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
A 404 generally means a disk space problem (or corrupted downloads?)

It exists:

<https://github.com/orgs/hassio-addons/packages/container/zwavejs2mqtt%2Famd64/2727632?tag=0.17.0>

From the add-on perspective, there is not much I can do, as the add-on itself is not involved in this part.

**Comment by maggar** [comment]
Something happened during the auto-update process that corrupted the install.  It's extremely unlikely that it's a disk issue as the VM is on a RAID array (Synology).  If anyone else has the same issue, please pile on, else I guess we'll call it unlucky for me.

I removed and re-installed it.  I had to add the path to the zwave stick and network key in the config (as expected, fortunately I had stored this in a text file off the VM for reference!), and now it's enumerating devices (all the hardwired devices came back quickly, the battery operated ones are taking a long time to connect, as expected).

**Comment by jimcortez** [comment]
I don't have any other data to add, except I got the same error. I have confirmed that there is 195GB of free space. This happened sometime overnight as I had the "auto-update" flag on.

When I hit "start" on the supervisor entry, I get

```
404 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_a0d7b954_zwavejs2mqtt: Not Found ("No such image: ghcr.io/hassio-addons/zwavejs2mqtt/armv7:0.17.0")
```

**Comment by frenck** [comment]
@jimcortez There is absolutely nothing on this end I can do about it.

Visit the URL to see for yourself:
<https://ghcr.io/hassio-addons/zwavejs2mqtt/armv7:0.17.0>

**Comment by jimcortez** [comment]
Yeah, totally understand, something else seems to have gone wrong, but I am guessing I won't be the first person to run into this. I agree that the package exists on the server.

I do see this in the supervisor logs, which is strange:
```
21-05-25 22:19:45 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-4355645' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
21-05-25 22:20:24 ERROR (SyncWorker_4) [supervisor.docker] Image ghcr.io/hassio-addons/zwavejs2mqtt/armv7 not exists for addon_a0d7b954_zwavejs2mqtt
```

**Comment by frenck** [comment]
`TypeError: an integer is required (got type str)`

That long error is caused by the Mosquitto add-on and is actually a bug in the Supervisor. This bug has been fixed and is pending release. However, it no related to this.

**Comment by jimcortez** [comment]
Very helpful to know, thanks! I tried restarting supervisor and no change.

A new suspicious log I found in my host's journalctl:

```
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 127.0.0.1:41125 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 64 true 2048" NOERROR - 0 0.000057962s
May 25 23:28:51 burrowpi d79fed478c9d[642]: [ERROR] plugin/errors: 2 a0d7b954-zwavejs2mqtt.local.hass.io. A: plugin/forward: no next plugin found
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,rd 53 0.001457339s
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000181591s
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000174646s
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000168554s
May 25 23:28:51 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000141406s
May 25 23:28:54 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000146258s
May 25 23:28:54 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000121758s
May 25 23:28:54 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000167517s
May 25 23:28:54 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000156165s
May 25 23:28:54 burrowpi d79fed478c9d[642]: [INFO] 172.30.32.1:35912 - 14364 "A IN a0d7b954-zwavejs2mqtt.local.hass.io. udp 53 false 512" SERVFAIL qr,aa,rd 53 0.000203794s
```

**Comment by frenck** [comment]
Try `ha supervisor repair` (and take a quick coffee break :D)

**Comment by jimcortez** [comment]
That did not fix anything. It seems this may be an unrelated issue: https://community.home-assistant.io/t/hass-io-cannot-use-local-dns-names-in-place-of-ip-addresses-in-configuration-yaml/159560/7?u=jimmybondo

**Comment by frenck** [comment]
That is not related. I'm sorry, but this is not something I can do anything about.

**Comment by jimcortez** [comment]
I finally just rebooted the host and everything came back. Thank you for the help!

**Comment by maggar** [comment]
Wondering what Jim  Cortez and my install have in common that is not common across every install.

One thing is that I used to run the ZwaveJS add-on and then converted to zwavejs2mqtt afterwards.

I'm also not running MQTT, just connected directly to my USB Nortek stick attached to HA (I wanted the control panel),

Running on a VM on a Synology NAS.

Version
core-2021.5.5
supervisor-2021.04.3
Home Assistant OS 5.13

**Comment by jimcortez** [comment]
@maggar I run a "supervised" install on raspbian. Same versions as you. I also switched to zwavejs2mqtt a while ago.

It seems to have been some weird dns issue, if you run into this problem, I recommend just rebooting your host, the problem was solved for me.

**Comment by sinclairpaul** [comment]
> Wondering what Jim  Cortez and my install have in common that is not common across every install.

>  I had the "auto-update" flag on

I honestly wish this option was removed from the Supervisor :), but yeah you might want to do controlled updates so you can see what else is going on at the time.

**Comment by maggar** [comment]
Yes, I had auto-update on too, and have since turned it off. 😊

To Jim’s point, I had tried rebooting but that didn’t work.  However, I did not do the ha supervisor repair first, so I’m wondering if that fixed it but you needed to reboot the host afterwards for it to take effect?

I re-installed and I wish I had tried the supervisor repair first (too impatient I guess).  Now I’m stuck with a handful of battery operated devices that are reluctant to get recognized… battery remove/insert seems to have worked for a few, but not all.
